elasticsearch:
  host: "{{ groups.backend[0] }}"
  ro:
    user: "{{ ro_user }}"
    pass: "{{ ro_pass }}"
  rw:
    user: "{{ rw_user }}"
    pass: "{{ rw_pass }}"
  index:
    prefix: "onestop-"

logging:
  level:
    ncei.onestop.api: DEBUG

ui:
  granuleDetails: true
  banner:
    message: THIS IS A BETA RELEASE - This site is not running on NCEI hardware, does not contain NCEI's full data holdings, and is only an partial implementation of its intended funtionality.