elasticsearch:
  host: "{{ groups.backend[0] }}"
  ro:
    user: "{{ ro_user }}"
    pass: "{{ ro_pass }}"
  rw:
    user: "{{ rw_user }}"
    pass: "{{ rw_pass }}"
  index:
    prefix: "onestop-"

logging:
  level:
    ncei.onestop.api: DEBUG

ui:
  granuleDetails: true
  banner:
    message: THIS IS A BETA RELEASE - IT IS NOT RUNNING ON NCEI HOSTS NOR DOES IT REPRESENT THE FULL EXTENT OF NCEI'S DATA