apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    environment: prod
    tier: backend
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-claim
spec:
  accessModes:
    - ReadWriteMany # R/W by many nodes
  resources:
    requests:
      storage: 1Gi # not sure what's reasonable?
