kafka:
  group.id: <group-id>
  bootstrap:
    servers: <kafka_host>:<kafka_port>

stream:
  input:
    topic: <input topic>
  split:
    - datastreamOne:
        key: <field in payload>
        value: <matching value>
        output:
          topic: <output topic>
    - datastreamTwo:
        key: <field in payload>
        value: <matching value>
        output:
          topic: <output topic>
