apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onestop-api-search.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "onestop-api-search.name" . }}
    helm.sh/chart: {{ include "onestop-api-search.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "onestop-api-search.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "onestop-api-search.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOST
              value: {{ .Values.elasticsearch.host }}
            - name: ELASTICSEARCH_PORT
              value: {{ .Values.elasticsearch.port }}
            - name: LOGIN_GOV_CLIENT_ID
              value: {{.Values.auth.clientId}}
            - name: LOGIN_GOV_ALLOWED_ORIGIN
              value: {{.Values.auth.allowedOrigin}}
            - name: LOGIN_GOV_LOGIN_SUCCESS_REDIRECT
              value: {{.Values.auth.endpoints.loginSuccessRedirect}}
            - name: LOGIN_GOV_LOGIN_FAILURE_REDIRECT
              value: {{.Values.auth.endpoints.loginFailureRedirect}}
            - name: LOGIN_GOV_LOGOUT_SUCCESS_REDIRECT
              value: {{.Values.auth.endpoints.logoutSuccessRedirect}}
            - name: LOGIN_GOV_KEYSTORE_FILE
              value: {{.Values.auth.keystoreFile}}
            - name: LOGIN_GOV_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logingov
                  key: KEYSTORE_PASSWORD
            - name: LOGIN_GOV_KEYSTORE_ALIAS
              valueFrom:
                secretKeyRef:
                  name: logingov
                  key: KEYSTORE_ALIAS
            - name: LOGIN_GOV_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logingov
                  key: KEY_PASSWORD
          {{- if .Values.search.config }}
            - name: spring.config.additional-location
              value: /etc/conf/application.yml
          {{- end }}

          volumeMounts:
          {{- if .Values.search.config }}
          - name: search-config-volume
              mountPath: /etc/conf/
          {{- end }}
          - name: keystore-volume
              mountPath: {{ include "onestop-api-admin.keystore.file" . | quote }}
              subPath: keystore.jks
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: keystore-volume
          secret:
            secretName: keystore-login-gov
            items:
              - key: KEYSTORE_FILE
                path: keystore.jks
        {{- if .Values.search.config }}
        - name: search-config-volume
          configMap:
            name: {{ include "onestop-api-search.fullname" . }}-config
        {{- end }}
#      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
