language: java
jdk:
  - oraclejdk8
notifications:
  email: false
  slack:
    rooms:
      - secure: Ch12lKiGgb6P1YrVkzhrAJrj+P4Bh4qcoPEVwBjUapRO02GbR7hJefYMAcBMbKv2CPQoHZHYaGn+XZ2//mIUdAW4fqjrKtY+Ep4EkhpBg8E/Hpu2TfKShOujIlnJfc4hxrzRK2mg/Avv4mUHIeLxDgzWGdNix7LHMLRi/aqsEYGH1llsa6vqfxXUta0FT9GlpaIDKF053gt3meAT+WPwpsu08NRWlb/JeXMW+PbP92HtUFbI40gAtCN8WCMRaEB4tQpkOlvEKo95NkU/ZdYZuGJ4ftOIGQW9ucxNBxOx4Hvv3qzX2hbQtx2WMLb3IJ6UvX3ybGjxozE6KwJsQHBVgJQl/6CBC8oVf5bcLJIW1LHPnUOXH2L/T4sVfATiKGFvJ/XAOFgJ4ylhjoud6NX98MhQD1D4OhiHi5wA4XJiqr7STBNO/uIHOU4vnbpUya/LeDRuoPmDgajTzp4VB0TlKfD3a3t3pfdBbxSgkG/e+8MLQVQMTUvwVeej0zRKNB/rvo9SbD+65NFzdL2DEhCEQGZrzHI+eKXftzhx6eDqM6u1Nhcka7yTu0weyzjldivDjCXZQ0eo9NsSclUKf3WmndPgD71pD01Dj57phoLxvc1zR5AD+bZ4VzXNxt3zBYHlHB8FTVmskp8ePp9A0kldS+b/tVeAHQmIuaxED1INXj4=
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .gradle
    - api/build
    - api/dist
    - client/.gradle
    - client/node_modules
    - client/build
install: true
script:
  - ./gradlew build -Dscan
before_deploy:
#  - secure: HJIBivyrseHFKmd5chWhNgnQqGDhB/PrZ9thrwoSRMds6ewIbw38yXT8Q/YnbG0Scs++oPoO7bDQkqOb2oL5cwsWSiFbHUvqYaf5Yjr5UTqzHyY9Kr1FNe0bXwKWmTYee0Dpa6SHUyxUYM9m8sU4h7mnmtaca65cj8CwmcJwNWP8Cu0kmzPhupUFNzZIzMEbDPj0pbX6BrBM9U/BMlvp+isY/cOSEgQ8V5b5Mvr/E7gAqJCwDWMbPP+rv7Y/sWRTH/gtYMFn9IFgsfqzCd/LyNoEvZK6EIdsxdO1Vz9iwL//g9RnIFgfEpjWAt+fPCgT+52nCJl/uWWT3EBzYLgOBPwqstX4cU8m8I5bzm/giq4tVT7VisQSLoXqATGNe5jbr42EwoG+40VFEB4Hi5LjpI+nhUhzeZQzDuQ6APQgwjIC1IpAO4beA/vOeBc0e1rebQ6mwMRxh1k84wfZ49OPCATXVQnf+X+OUQvMZCoVnpJSbeYLJ6tTV/tEDFHGBYnFniiAbczzQpDgtB+EfDDt9EUkMx1UzeR3dFLCEiSdANLNgL4IzDFDi88UKR1keV8+BEl5QEnb/4KfOVhihU3PSozpHft0z/qufThCfBfLkCy0pZs0uH+RVsd/Bav+8ENQcEHIdFr9jJfIZJzJRuYbuBBkv1ICR8dYz7s8vDjZhd8=
#  - secure: e/WVk0fQ4M1Evml8l2O1rmemCz0Zh18PYrCsbL8XmtVNDrhayNySiACmd6TxpO+QKX36oXTRPUbypDeuZprDaZQIgdRRYSkNgi0UV67cROQgl1hxlZVbxbFhZgKpCHSg3HJSc+kvXlXFCwK3+1bc8QJzOCWItG0hehWFhimJC4jpeaMKM3x9zXEmNH9aQeu/GVHcWz2viBGTBNRWOiKeh6yrR7UZ4V4JtvSgr3djaHbyRCEFBjwkWm5kUIlJGgF8Gx2BPHaTW+GMVj8Oe+4y2i1IsLPfVDXaGp2bqtx1eNSj/v8j/QMa4xmJjKl/Axtw+Joe0ipcoqfvTdVy2BeZ7ZAm8Ha5DsNsxURBFfhmoby1FsTY5lgLqT8n9RxRr8g+ndfKIEK4A3xUYvD2YVxzJpnKGH7gAQK5oJFG+teQdTILZZLTjeY4vvPWmxSWWBBxj0jJMm6yqw9BevR8pT4JZ/rzoIUn2KqGpjbCjcNU1Hqxv3v23USBvZhgxvg4aIX9SB0irCr74OtLXD8MjZnYlvuKFOaUaPtERTrRGyC1h2h30IvVbOWRZLJdiqITUxkbBemEP6DHKmuu09ikLY22p9EMJYwvhJRWD29C6KebibHsM/Pe+OCqBwvGbsbPf/kJEO6wzo4Wxkv4LvKGNU0qs9Ev0LEBK2nMJGwRscYjydU=
#deploy:
#  skip_cleanup: true
#  script: ./gradlew artifactoryPublish
#  on:
#    repo: cires-ncei/onestop
