version: '3'

services:
  client:
    image: cedardevs/onestop-client:latest
    ports:
      - 8080:80
    depends_on:
      - api-search
    environment:
      - UPSTREAM_HOST=api-search

  api-search:
    image: cedardevs/onestop-api-search:latest
    ports:
      - 8097:8097
    depends_on:
      - elasticsearch
    environment:
      - elasticsearch_host=elasticsearch
      - elasticsearch_port=9200
      - logging_level_org.cedar.onestop.api=DEBUG

  api-metadata:
    image: cedardevs/onestop-api-metadata:latest
    ports:
      - 8098:8098
    depends_on:
      - elasticsearch
    environment:
      - elasticsearch_host=elasticsearch
      - elasticsearch_port=9200
      - logging_level_org.cedar.onestop.api=DEBUG

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-5.5.1}
    environment:
      - xpack.security.enabled=false
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - ./build/elasticsearch/data:/usr/share/elasticsearch/data
