version: '3'
services:
  client:
    build: ./client/
    ports:
     - 8080:80
    depends_on:
      - api

  api:
    build: ./api/
    ports:
      - 8097:8097
    depends_on:
      - elasticsearch
    environment:
     - elasticsearch_host=elasticsearch
     - elasticsearch_port=9300

  elasticsearch:
    build: ./elasticsearch/docker-es/
    ports:
     - 9300:9300
     - 9200:9200
