version: '3'
services:
  client:
    build:
      context: ./client/
      args:
        VERSION: ${VERSION}
        DATE: ${DATE}
        VCS_REF: ${VCS_REF}
    environment:
      - "ONESTOP_ENDPOINT=api:8097"
      - "GEOPORTAL_ENDPOINT=geoportal-search:8080"
    ports:
     - 8080:80
    depends_on:
      - api

  api:
    build:
      context: ./api/
      args:
        VERSION: ${VERSION}
        DATE: ${DATE}
        VCS_REF: ${VCS_REF}
        JAR_NAME: onestop-api-all
    ports:
      - 8097:8097
    depends_on:
      - elasticsearch
    environment:
     - elasticsearch_host=elasticsearch
     - elasticsearch_port=9300

  geoportal-search:
    image: cedardevs/onestop-geoportal-search:latest
    depends_on:
      - elasticsearch
    ports:
      - 8080
    environment:
      - "ELASTICSEARCH_ENDPOINT=http://elasticsearch:9200/search/granule/_search"

  elasticsearch:
    build: ./elasticsearch/docker-es/
    ports:
     - 9300:9300
     - 9200:9200
