version: '2'
services:
  client:
    build: ./client/docker-client/
    volumes:
     - ./client/dist:/usr/share/nginx/html:ro
    ports:
     - 8080:80
    depends_on:
      - api

  api:
    build: ./api/docker-api/
    volumes:
      - ./api/build/libs/onestop-api-all-1.1.1-SNAPSHOT.war:/usr/local/tomcat/webapps/onestop.war
    ports:
      - 8097:8097
    depends_on:
      - elasticsearch

  elasticsearch:
    build: ./elasticsearch/docker-es/
    ports:
     - 9300:9300
     - 9200:9200
