version: '3'
services:
  client:
    build: ./client/
    ports:
     - 8080:80
    depends_on:
      - api

  api:
    build: ./api/
    ports:
      - 8097:8097
    depends_on:
      - elasticsearch

  elasticsearch:
    build: ./elasticsearch/docker-es/
    ports:
     - 9300:9300
     - 9200:9200
    volumes:
     - ./elasticsearch/build/elasticsearch/elasticsearch-2.4.1/data:/usr/share/elasticsearch/data
