apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: cedardevs/psi-registry
    context: ./registry
    docker:
      buildArgs:
        DATE: now
        JAR_NAME: psi-registry-0.2.0-SNAPSHOT-all.jar
        VCS_REF: local
        VERSION: 0.2.0-SNAPSHOT
  - image: cedardevs/psi-stream-manager
    context: ./stream-manager
    docker:
      buildArgs:
        DATE: now
        JAR_NAME: psi-stream-manager-0.2.0-SNAPSHOT-all.jar
        VCS_REF: local
        VERSION: 0.2.0-SNAPSHOT
deploy:
  helm:
    releases:
    - name: psi-registry
      chartPath: helm/psi/psi-registry
      values:
        image: cedardevs/psi-registry
      setValues:
        kafka.bootstrapServers: PLAINTEXT://psi-dev-cp-kafka:9092
      imageStrategy:
        helm: {}
    - name: psi-manager
      chartPath: helm/psi/psi-manager
      values:
        image: cedardevs/psi-stream-manager
      setValues:
        kafka.bootstrapServers: PLAINTEXT://psi-dev-cp-kafka:9092
      imageStrategy:
        helm: {}
    - name: psi-dev
      chartPath: helm/psi-dev
