apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: cedardevs/onestop-api-metadata
    workspace: ./api-metadata
    docker:
      buildArgs:
        WAR_NAME: api-metadata-2.1.0-all.war
        VERSION: 2.1.0
        DATE: now
        VCS_REF: local
  - imageName: cedardevs/onestop-api-search
    workspace: ./api-search
    docker:
      buildArgs:
        WAR_NAME: api-search-2.1.0-all.war
        VERSION: 2.1.0
        DATE: now
        VCS_REF: local
  - imageName: cedardevs/onestop-client
    workspace: ./client
    docker:
      buildArgs:
        VERSION: 2.1.0
        DATE: now
        VCS_REF: local
        TAR_NAME: onestop-client-2.1.0.tar.gz

deploy:
  kubectl:
    manifests:
    - ./kubernetes/deployments/elasticsearch.yaml
    - ./kubernetes/deployments/onestop-api-metadata.yaml
    - ./kubernetes/deployments/onestop-api-search.yaml
    - ./kubernetes/deployments/onestop-client.yaml
    #- ./kubernetes/deployments/onestop-logstash.yaml
    #- ./kubernetes/deployments/filebeat-kubernetes.yaml
    #- ./kubernetes/deployments/kibana.yaml
    # TODO: geoportal-search
    
