apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: cedardevs/psi-registry
    context: ./registry
    docker:
      buildArgs:
        DATE: now
        JAR_NAME: psi-registry-1.0.0-SNAPSHOT-all.jar
        VCS_REF: local
        VERSION: 1.0.0-SNAPSHOT
  - image: cedardevs/psi-stream-manager
    context: ./stream-manager
    docker:
      buildArgs:
        DATE: now
        JAR_NAME: psi-stream-manager-1.0.0-SNAPSHOT-all.jar
        VCS_REF: local
        VERSION: 1.0.0-SNAPSHOT
deploy:
  helm:
    releases:
    - name: psi-registry
      chartPath: helm/psi-registry
      values:
        image: cedardevs/psi-registry
      setValues:
        # features are directly tied to `export SPRING_PROFILES_ACTIVE='cas,...'
        # all features default to "false" in base chart, unless otherwise overridden
        features.cas: false
        config: |-
          ---
          logging.level.org.cedar: DEBUG
          server.servlet.context-path: /registry
          kafka.commit.interval: 1000
        cp-schema-registry.url: http://psi-dev-cp-schema-registry:8081
        kafka.bootstrapServers: PLAINTEXT://psi-dev-cp-kafka:9092
      imageStrategy:
        helm: {}
    - name: psi-manager
      chartPath: helm/psi-manager
      values:
        image: cedardevs/psi-stream-manager
      setValues:
        config: |-
          ---
          logging.level.org.cedar: DEBUG
          kafka.commit.interval: 1000
        cp-schema-registry.url: http://psi-dev-cp-schema-registry:8081
        kafka.bootstrapServers: PLAINTEXT://psi-dev-cp-kafka:9092
      imageStrategy:
        helm: {}
    - name: psi-dev
      chartPath: helm/psi-dev
