apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: cedardevs/psi-registry
    workspace: ./registry
    docker:
      buildArgs:
        JAR_NAME: registry-0.1.0-SNAPSHOT-all.jar
        VERSION: 0.1.0-SNAPSHOT
        DATE: now
        VCS_REF: local
  - imageName: cedardevs/psi-stream-manager
    workspace: ./stream-manager
    docker:
      buildArgs:
        JAR_NAME: stream-manager-0.1.0-SNAPSHOT-all.jar
        VERSION: 0.1.0-SNAPSHOT
        DATE: now
        VCS_REF: local
deploy:
  kubectl:
    manifests:
    - ./kubernetes/zookeeper.yml
    - ./kubernetes/kafka.yml
    - ./kubernetes/kafka-rest.yml
    - ./kubernetes/kafka-ui.yml
    - ./kubernetes/registry.yml
    - ./kubernetes/stream-manager.yml