apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: cedardevs/psi-registry
    jibGradle:
      project: registry
  - image: cedardevs/psi-stream-manager
    jibGradle:
      project: stream-manager

deploy:
  helm:
    releases:
    - name: psi-registry
      chartPath: helm/psi-registry
      values:
        image: cedardevs/psi-registry
      setValues:
        # features are directly tied to `export SPRING_PROFILES_ACTIVE='cas,...'
        # all features default to "false" in base chart, unless otherwise overridden
        features.cas: true
        # if true, `kubectl port-forward psi-registry-0 5005:5005` to expose JDWP for debugging
        # then,
        debug: true
        config: |-
          ---
          logging.level.org.cedar: DEBUG
          logging.level.org.pac4j.springframework.web: TRACE
          logging.level.org.pac4j.core.engine: TRACE
          logging.level.org.pac4j.cas: TRACE
          server.servlet.context-path: /registry
          kafka.commit.interval: 1000
          topics:
            num-partitions: 20
            replication-factor: 1
        # env values
        kafka.schema.registry.url: http://psi-dev-cp-schema-registry:8081
        kafka.bootstrap.servers: PLAINTEXT://psi-dev-cp-kafka:9092
      imageStrategy:
        helm: {}
    - name: psi-manager
      chartPath: helm/psi-manager
      values:
        image: cedardevs/psi-stream-manager
      setValues:
        config: |-
          ---
          logging.level.org.cedar: DEBUG
          kafka.commit.interval: 1000
        # Env values
        kafka.schema.registry.url: http://psi-dev-cp-schema-registry:8081
        kafka.bootstrap.servers: PLAINTEXT://psi-dev-cp-kafka:9092
      imageStrategy:
        helm: {}
    - name: psi-dev
      chartPath: helm/psi-dev
profiles:
- name: registry
  patches:
  # remove the psi-manager from the build and deployment
  - op: remove
    path: /build/artifacts/1
  - op: remove
    path: /deploy/helm/releases/1
- name: manager
  patches:
  # remove the psi-manager from the build and deployment
  - op: remove
    path: /build/artifacts/0
  - op: remove
    path: /deploy/helm/releases/0
