apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: cedardevs/psi-registry
    jibGradle:
      project: registry
  - image: cedardevs/psi-stream-manager
    jibGradle:
      project: stream-manager

deploy:
  helm:
    releases:
    - name: psi-registry
      chartPath: helm/psi-registry
      values:
        image: cedardevs/psi-registry
      setValues:
        # features are directly tied to `export SPRING_PROFILES_ACTIVE='cas,...'
        # all features default to "false" in base chart, unless otherwise overridden
        features.cas: false
        config: |-
          ---
          logging.level.org.cedar: DEBUG
          server.servlet.context-path: /registry
          kafka.commit.interval: 1000
          topics:
            num-partitions: 2
            replication-factor: 1
        # env values
        kafka.schema.registry.url: http://psi-dev-cp-schema-registry:8081
        kafka.bootstrap.servers: PLAINTEXT://psi-dev-cp-kafka:9092
#        autoscaler.enabled: true
#        autoscaler.maxReplicas: 2
#        autoscaler.cpu.averageValue: 150m
      imageStrategy:
        helm: {}
    - name: psi-manager
      chartPath: helm/psi-manager
      values:
        image: cedardevs/psi-stream-manager
      setValues:
        config: |-
          ---
          logging.level.org.cedar: DEBUG
          kafka.commit.interval: 1000
        # Env values
        kafka.schema.registry.url: http://psi-dev-cp-schema-registry:8081
        kafka.bootstrap.servers: PLAINTEXT://psi-dev-cp-kafka:9092
#        autoscaler.enabled: true
#        autoscaler.maxReplicas: 2
#        autoscaler.cpu.averageValue: 150m
      imageStrategy:
        helm: {}
    - name: psi-dev
      chartPath: helm/psi-dev
profiles:
- name: registry
  patches:
  # remove the psi-manager from the build and deployment
  - op: remove
    path: /build/artifacts/1
  - op: remove
    path: /deploy/helm/releases/1
- name: manager
  patches:
  # remove the psi-manager from the build and deployment
  - op: remove
    path: /build/artifacts/0
  - op: remove
    path: /deploy/helm/releases/0
