apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: cedardevs/onestop-api-metadata
    context: ./api-metadata
    docker:
      buildArgs:
        DATE: now
        VCS_REF: local
        VERSION: 2.1.0
        WAR_NAME: onestop-metadata-2.1.0.war
  - image: cedardevs/onestop-api-search
    context: ./api-search
    docker:
      buildArgs:
        DATE: now
        VCS_REF: local
        VERSION: 2.1.0
        WAR_NAME: onestop-search-2.1.0.war
  - image: cedardevs/onestop-client
    context: ./client
    docker:
      buildArgs:
        DATE: now
        VCS_REF: local
        VERSION: 2.1.0
        TAR_NAME: onestop-client-2.1.0.tar.gz

deploy:
  helm:
    releases:
    ###############################################################################
    # ELASTICSEARCH
    ###############################################################################
    - name: elasticsearch
      chartPath: helm/elasticsearch
      setValues:
        enabled: true
        # allows elasticsearch to be exposed outside the cluster in dev
        service.type: NodePort
        service.nodePort: 30092
    ###############################################################################
    # KIBANA
    ###############################################################################
    # - name: kibana
    #   chartPath: helm/kibana
      # setValues:
        # enabled: true
        # allows kibana to be exposed outside the cluster in dev
        # service.type: NodePort
        # service.nodePort: 32001
    ###############################################################################
    # API ADMIN
    ###############################################################################
    - name: api-admin
      chartPath: helm/api-admin
      values:
        # skaffold may not build/deploy w/the latest if this is not set here
        image: cedardevs/onestop-api-metadata
      imageStrategy:
        helm: {}
      setValues:
        # allows api-admin to be exposed outside the cluster in dev
        # features are directly tied to `export SPRING_PROFILES_ACTIVE='feat1,feat2,...'
        # all features default to "false" in base chart, unless otherwise overridden
        features.icam: false
        features.manual-upload: false
        features.kafka-ingest: false
        features.sitemap: false
        env.ELASTICSEARCH_HOST: elasticsearch
        config: |-
          ---
          logging.level.org.cedar.onestop.api.metadata: DEBUG
    ###############################################################################
    # API SEARCH
    ###############################################################################
    - name: api-search
      chartPath: helm/api-search
      values:
        # skaffold may not build/deploy w/the latest if this is not set here
        image: cedardevs/onestop-api-search
      imageStrategy:
        helm: {}
      setValues:
        # allows api-search to be exposed outside the cluster in dev
        # features are directly tied to `export SPRING_PROFILES_ACTIVE='feat1,feat2,...'
        # all features default to "false" in base chart, unless otherwise overridden
        features.login-gov: false
        # login.gov configuration that are later read as environment variables by Spring
        # these values override the chart's default sciapps config in order to run locally for dev
        loginGov.clientId: "urn:gov:gsa:openidconnect.profiles:sp:sso:NOAA:onestop_api_search_localhost_8080"
        loginGov.allowedOrigin: "http://localhost:8080"
        loginGov.endpoints.loginSuccessRedirect: "http://localhost:8080/onestop/"
        loginGov.endpoints.loginFailureRedirect: "http://localhost:8080/onestop/"
        loginGov.endpoints.logoutSuccessRedirect: "http://localhost:8080/onestop/"
        env.ELASTICSEARCH_HOST: elasticsearch
        # config: |-
        #   ---
        #   logging.level.org.cedar.onestop.api.search: DEBUG
    ###############################################################################
    # CLIENT
    ###############################################################################
    - name: client
      chartPath: helm/client
      values:
        # skaffold may not build/deploy w/the latest if this is not set here
        image: cedardevs/onestop-client
      imageStrategy:
        helm: {}
      setValues:
        # allows api-search to be exposed outside the cluster in dev
        prefixPath: onestop
        apiSearch.endpoint: api-search:8080/onestop-search
    ###############################################################################
    # DEV DEPENDENCIES
    ###############################################################################
    - name: onestop-dev
      chartPath: helm/onestop-dev
