---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "psi-registry.fullname" . }}
  labels:
    app: {{ template "psi-registry.name" . }}
    chart: {{ template "psi-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ template "psi-registry.fullname" . }}-mapping
      prefix: /registry/
      service: {{ template "psi-registry.fullname" . }}:{{ .Values.service.port }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "psi-registry.name" . }}
    release: {{ .Release.Name }}
