apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kibana.fullname" . }}-config
  labels:
    app: {{ template "kibana.name" . }}
    chart: {{ template "kibana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kibana.yml: |-
    server.basePath: /kibana
    server.host: 0.0.0.0
    elasticsearch.url: "http://{{ template "elasticsearch.serviceName" . }}:{{ .Values.elasticsearch.port }}"
    xpack.monitoring.ui.container.elasticsearch.enabled: false
