# global is 1st priority in subcharts
#
# This prevents possible deviation of shared, hardcoded values in subcharts.
# For known shared values among subcharts, you must graceful fallback value.
# (e.g. - `{{ .Values.global.? | default .Values.? }}
# 
# IMPORTANT: apply the pattern in all places the shared value occurs!
#
# These values could be overridden for each chart in this parent chart;
# however, this also fails to prevent hardcoding redundant values -- it
# simply isolates the redundancy to a single file. This `global` block
# allows us to quickly do things like change the port `elasticsearch` runs
# on in a 'dev' environment. The `onestop-api-admin` service relies on
# an environment variable set to this same port, but it won't break in
# this case as long as the global-plus-fallback value pattern shown
# above is used in ALL subchart templates where this port is referenced.
global:
  elasticsearch:
    enabled: true
    host: elasticsearch
    port: 9200
    portTransport: 9300

elasticsearch:
  enabled: true
  # allows elasticsearch to be exposed outside the cluster in dev
  service.type: NodePort
  service.nodePort: 30092

onestop-api-admin:
  enabled: true
  # allows onestop-api-admin to be exposed outside the cluster in dev
  service.type: NodePort
  service.nodePort: 30097
  features:
    security: false
    kafka: false
  config: |-
    ---
    logging.level.org.cedar.onestop.api: DEBUG

# onestop-api-search:
#   auth:
#     clientId: "urn:gov:gsa:openidconnect.profiles:sp:sso:NOAA:SciAppsOneStop"
#     allowedOrigin: "https://sciapps.colorado.edu"
#     endpoints:
#       loginSuccessRedirect: "/"
#       loginFailureRedirect: "/"
#       logoutSuccessRedirect: "/"
#     keystoreFile: "/etc/api-search/logingov.jks"