

###############################################################################
# KIBANA
###############################################################################
kibana:
  enabled: true
  service:
    type: NodePort
    nodePort: 32001
