---
apiVersion: v1
kind: Service
metadata:
  name: kafka-rest
  labels:
    app: kafka-rest
spec:
  selector:
    app: kafka-rest
  ports:
    - name: http
      port: 8080
      targetPort: http

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-rest
  labels:
    app: kafka-rest
spec:
  selector:
    matchLabels:
      app: kafka-rest
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
        - name: kafka-rest
          image: confluentinc/cp-kafka-rest:4.1.1
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "unset KAFKA_REST_PORT && /etc/confluent/docker/run"]
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KAFKA_REST_HOST_NAME
              value: "kafka-rest"
            - name: KAFKA_REST_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_REST_LISTENERS
              value: "http://0.0.0.0:8080"
