kafka:
  group.id: <group-id>
  bootstrap:
    servers: <kafka_host>:<kafka_port>

stream:
  topics:
      input: <input_topic>
      output: <output_topic>
  command: <run a bash command or execute a script>
  command_timeout: <timeout_ms>