kafka:
  group.id: <group-id>
  bootstrap:
    servers: <kafka_host>:<kafka_port>
  topics:
    input: <input_topic>
    output: <output_topic>

alg:
  absolutePath: <absolute>/<path>/<to>/<script>.py
  lang: <language>
  timeout: 5000