# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify stream dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # build it!
      - run:
          name: Build
          command: ./gradlew build

      - run:
          name: Save test results
          command: |
            mkdir -p ~/tests/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/tests/junit/ \;
            find . -type f -regex ".*/build/integration-test-results/.*xml" -exec cp {} ~/tests/junit/ \;
          when: always

      - run:
          name: Save jacoco results
          command: |
            mkdir -p ~/tests/jacoco/
            find . -type d -regex ".*/build/reports/jacoco/" -exec cp -r {} ~/tests/jacoco/ \;
          when: always

      - run:
          name: Post jacoco results to codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: ~/tests

      - store_artifacts:
          path: ~/tests

      - save_cache:
          paths:
            - ~/.gradle
            - .gradle
            - api/build
            - parser/build
            - registry/build
            - script-wrapper/build
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - deploy:
          name: Publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "release/*" ]; then
              ./gradlew publish -x BuildDockerImage
            fi

### configure via the ui
#notify:
#  webhooks:
#    # A list of hashes representing hooks. Only the url field is supported.
#    - url: https://hooks.slack.com/services/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
