apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api-search
  name: api-search
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api-search
    spec:
      containers:
      - env:
        - name: elasticsearch_host
          value: elasticsearch
        - name: elasticsearch_port
          value: "9200"
        - name: logging_level_org.cedar.onestop.api
          value: DEBUG
        - name: spring.config.additional-location
          value: /opt/onestop-api/onestop-ui-local.yml
        image: cedardevs/onestop-api-search:latest
        name: api-search
        ports:
        - containerPort: 8097
        resources: {}
        volumeMounts:
        - mountPath: /opt/onestop-api/
          name: api-search-claim0
      restartPolicy: Always
      volumes:
      - name: api-search-claim0
        persistentVolumeClaim:
          claimName: api-search-claim0
status: {}
