apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    environment: dev
    tier: backend
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
  type: ClusterIP
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: elasticsearch-pv-claim
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce # R/W by one node (aka minikube)
#  resources:
#    requests:
#      storage: 100Mi # plenty for local env
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3 # use gradle ${ES_VERSION:-5.5.3} in future
        resources:
          limits:
            memory: 1Gi # match ES_JAVA_OPTS
          requests:
            memory: 256Mi # match ES_JAVA_OPTS
        env:
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.watcher.enabled
          value: "false"
        - name: xpack.monitoring.enabled
          value: "false"
        - name: xpack.ml.enabled
          value: "false"
        - name: xpack.graph.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m # may need more memory
        - name: CLUSTER_NAME
          value: elasticsearch # default name; should be variable in prod
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
#        volumeMounts:
#        - name: storage
#          mountPath: "/data"
#      volumes:
#      - name: storage
#        persistentVolumeClaim:
#          claimName: elasticsearch-pv-claim
#      restartPolicy: Always
