{{ if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "psi-registry.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "psi-registry.name" . }}
    helm.sh/chart: {{ include "psi-registry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yaml: {{ .Values.config | toYaml | nindent 4 }}
{{- end }}
