---
kafka:
  bootstrap:
    servers: "localhost:9092"
  schema:
    registry:
      url: "http://localhost:8081"
  fetch:
    max:
      wait:
        ms: 300000  # 5 min
  max:
    poll:
      records: 20
  auto:
    offset:
      reset: "earliest"
  topic:
    granules: "psi-registry-granule-parsed-changelog"
    collections: "psi-registry-collection-parsed-changelog"

