---
server:
  port: 8098
  servlet:
    context-path: /onestop-admin

spring:
  application:
    name: onestop-admin
  jmx:
    default-domain: onestop-admin

management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true

logging:
  level:
    org.cedar.onestop.api.admin: INFO
    org.gradle: WARN
    org.apache.http: WARN
    org.apache.http.wire: WARN
    org.apache.http.headers: WARN
    groovyx.net.http: WARN
    groovyx.net.http.HttpURLClient: WARN
    org.springframework: INFO
    org.springframework.amqp: WARN
    org.hibernate: WARN

elasticsearch:
  version: ${esVersion}
  host: localhost
  port: 9200
  max-tasks: 10

info.version: ${version}
info.buildDate: ${buildDate}
