---
server:
  port: 8080
management.endpoints.enabled-by-default: false

publishing:
  interval:
    ms: 300000

logging:
  level:
    root: INFO
    org.springframework.web: ERROR

topics:
  num-partitions: 20
  replication-factor: 3
