---
server.port: 8080
management.endpoints.enabled-by-default: false

kafka:
  bootstrap:
    servers: localhost:9092
  topics:
    raw:
      granule: granule-events
      collection: collection-events
  stores:
    raw:
      granule: raw-granule
      collection: raw-collection

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
