---
server:
  port: 8080
  servlet:
    context-path: "/registry"
management.endpoints.enabled-by-default: false

kafka:
  bootstrap:
    servers: localhost:9092

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
