---
# -- allows for better security logs for debugging --
#logging.level.org.pac4j.springframework.web: DEBUG
#logging.level.org.pac4j.core.engine: DEBUG
#logging.level.org.pac4j.cas: DEBUG

# -- point to the actual CAS server --
# -- note: will require actually registering service in the future...
#cas:
#  prefixUrl: 'https://auth.ncdc.noaa.gov/cas'

# -- point to the local dev CAS server built from the CAS Overlay --
# -- note: uses our own baked-in JSON registry to know of this service
cas:
  prefixUrl: 'http://psi-dev-cas:8080/cas'

authorization:
  roles:
    ROLE_ADMIN:
      - casuser
      - elliott.richerson



