---
server.port: 8080
management.endpoints.enabled-by-default: false

kafka:
  bootstrap:
    servers: localhost:9092
schema:
  registry:
    url: localhost:8081

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
