---
dependencies:
  - name: elasticsearch
    version: ~0.1.0
    repository: file://../elasticsearch
    condition: elasticsearch.enabled,global.elasticsearch.enabled
  - name: onestop-admin
    version: ~0.1.0
    repository: file://../onestop-admin
    conditions: onestop-admin.enabled,global.onestop-admin.enabled
  - name: onestop-search
    version: ~0.1.0
    repository: file://../onestop-search
    conditions: onestop-search.enabled,global.onestop-search.enabled
  # - name: onestop-user
  #   version: ~0.1.0
  #   repository: file://../onestop-user
  #   conditions: onestop-user.enabled,global.onestop-user.enabled
  - name: onestop-client
    version: ~0.1.0
    repository: file://../onestop-client
    conditions: onestop-client.enabled,global.onestop-client.enabled
