spring.profiles.include:
  - default

# comma-delimited string (no spaces)
# auth feature toggle: securityenabled | securitydisabled
# other features: ...
spring.profiles.active: "securitydisabled"

server:
  port: 8098
  servlet:
    context-path: /onestop/api

spring:
  application:
    name: onestop-metadata-api

management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true

features.secure.upload: true
features.sitemap: false

etl:
  sitemap:
    delay:
      initial: 600000
      fixed: 604800000
    scroll-size: 10000
    collections-per-submap: 40000

logging:
  level:
    org.cedar.onestop.api.metadata: INFO
    org.gradle: WARN
    org.apache.http: WARN
    org.apache.http.wire: WARN
    org.apache.http.headers: WARN
    groovyx.net.http: WARN
    groovyx.net.http.HttpURLClient: WARN
    org.springframework: INFO
    org.springframework.amqp: WARN
    org.hibernate: WARN

elasticsearch:
  version: ${esVersion}
  host: localhost
  port: 9200
  max-tasks: 10
  index:
    universal-type: doc
    sitemap:
      name: sitemap
    search:
      collection:
        name: search_collection
        pipeline-name: collection_pipeline
      granule:
        name: search_granule
        pipeline-name: granule_pipeline
      flattened-granule:
        name: search_flattened_granule
    staging:
      collection:
        name: staging_collection
      granule:
        name: staging_granule

info.version: ${version}

kafka:
  bootstrap:
    servers: kafka:9092
    max_poll_records: 20
    max_wait_ms: 300000  # 5 min
  topic:
    PARSED_GRANULES_TOPIC: 'metadata-aggregator-parsed-granules-changelog'
    PARSED_COLLECTIONS_TOPIC: 'metadata-aggregator-parsed-collections-changelog'
#  topics: metadata-aggregator-parsed-granules-changelog, metadata-aggregator-parsed-collections-changelog