# comment out security.ignored if SAML Authentication Feature is enabled. The other features must be flipped
# in order to feature toggle the Authentication + Authorization Feature
security.ignored: /**
features.secure.upload: false
features.secure.authorization: false
features.basicAuth.disabled: true

roles.names: ADMIN;USER
user.roles: elliott.richerson@noaa.gov:ADMIN;bao.nguyen@noaa.gov:ADMIN

server:
  port: 8098
  servlet:
    context-path: /onestop/api
  # Comment out everything between the dashes if Auth Feature is disabled
  # -----------------------------------------------------------------
#  ssl:
#    key-alias: \${KEYSTORE_ALIAS}
#    #key-password: \${KEY_PASSWORD}
#    enabled-protocols: TLSv1.2
#    protocol: TLS
#    enabled: true
#    key-store-password: \${KEYSTORE_PASSWORD}
#    key-store: /Users/elliott/Documents/GitHub/help/keystores/sciapps.colorado.edu.jks
#    key-store-type: JKS
  # -----------------------------------------------------------------

# SAML Identity Provider Configuration
# - comment out between dashes if Auth Feature is disabled
# -----------------------------------------------------------------
# ICAM (sciapps)
# -----------------------------------------------------------------
#identityProvider:
#  name: "ICAM (sciapps)"
#  loginEndpoint: "https://sso-dev.lb.csp.noaa.gov:443/openam/SSOPOST/metaAlias/noaa-online/noaa-online-idp"
#  loginBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#  logoutEndpoint: "https://sso-dev.lb.csp.noaa.gov:443/openam/IDPSloRedirect/metaAlias/noaa-online/noaa-online-idp"
#  logoutBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#  issuerSP: "https://sciapps.colorado.edu/onestop/api/"
#  issuerIDP: "noaa-online-idp"
#  authnContextRefs:
#    - "urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified"
#  authnContextComparisonType: "minimum"
#  assertionConsumerServiceURL: "https://sciapps.colorado.edu/onestop/api/loginConsume"
#  assertionConsumerServiceLogoutURL: "https://sciapps.colorado.edu/onestop/api/logoutConsume"
#  nameIDPolicyFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
##  forceAuthn: null
##  isPassive: null
#  signatureAlgorithm: "http://www.w3.org/2000/09/xmldsig#rsa-sha1"
#  signatureCanonicalizationAlgorithm: "http://www.w3.org/2001/10/xml-exc-c14n#"
#  digestAlgorithm: "http://www.w3.org/2000/09/xmldsig#sha1"
#  emailAssertionName: "mail"
##  emailAssertionNameFormat: null
#  uuidAssertionName: "uid"
##  uuidAssertionNameFormat: null
# -----------------------------------------------------------------
# ICAM (localhost)
# -----------------------------------------------------------------
#identityprovider:
#  name: "ICAM (localhost)"
#  loginEndpoint: "https://sso-dev.lb.csp.noaa.gov:443/openam/SSOPOST/metaAlias/noaa-online/noaa-online-idp"
#  loginBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#  logoutEndpoint: "https://sso-dev.lb.csp.noaa.gov:443/openam/IDPSloRedirect/metaAlias/noaa-online/noaa-online-idp"
#  logoutBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#  issuerSP: "https://localhost:8098/onestop/api/"
#  issuerIDP: "noaa-online-idp"
#  authnContextRefs:
#    - "urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified"
#  authnContextComparisonType: "minimum"
#  assertionConsumerServiceURL: "https://localhost:8098/onestop/api/loginConsume"
#  assertionConsumerServiceLogoutURL: "https://localhost:8098/onestop/api/logoutConsume"
#  nameIDPolicyFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
#  forceAuthn: null
#  isPassive: null
#  signatureAlgorithm: "http://www.w3.org/2000/09/xmldsig#rsa-sha1"
#  signatureCanonicalizationAlgorithm: "http://www.w3.org/2001/10/xml-exc-c14n#"
#  digestAlgorithm: "http://www.w3.org/2000/09/xmldsig#sha1"
#  emailAssertionName: "mail"
##  emailAssertionNameFormat: null
#  uuidAssertionName: "uid"
##  uuidAssertionNameFormat: null
# -----------------------------------------------------------------
# login.gov (sciapps)
# -----------------------------------------------------------------
#identityProvider:
#  name: "login.gov (sciapps)"
#  loginEndpoint: "https://idp.int.identitysandbox.gov/api/saml/auth"
#  loginBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
#  logoutEndpoint: "https://idp.int.identitysandbox.gov/api/saml/logout"
#  logoutBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#  issuerSP: "urn:gov:gsa:SAML:2.0.profiles:sp:sso:NOAA:authentication_sciapps"
#  issuerIDP: "https://idp.int.identitysandbox.gov/api/saml"
#  authnContextRefs:
#    - "http://idmanagement.gov/ns/assurance/loa/1"
#    - "http://idmanagement.gov/ns/requested_attributes?ReqAttr=email"
#  authnContextComparisonType: "minimum"
#  assertionConsumerServiceURL: "https://sciapps.colorado.edu/onestop/api/loginConsume"
#  assertionConsumerServiceLogoutURL: "https://sciapps.colorado.edu/onestop/api/logoutConsume"
#  nameIDPolicyFormat: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
#  forceAuthn: false
#  isPassive: true
#  signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
#  signatureCanonicalizationAlgorithm: "http://www.w3.org/2001/10/xml-exc-c14n#"
#  digestAlgorithm: "http://www.w3.org/2001/04/xmlenc#sha256"
#  emailAssertionName: "email"
#  emailAssertionNameFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
#  uuidAssertionName: "uuid"
#  uuidAssertionNameFormat: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
# -----------------------------------------------------------------
# login.gov (localhost)
# -----------------------------------------------------------------
#identityProvider:
#  name: "login.gov (localhost)"
#  loginEndpoint: "https://idp.int.identitysandbox.gov/api/saml/auth"
#  loginBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
#  logoutEndpoint: "https://idp.int.identitysandbox.gov/api/saml/logout"
#  logoutBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
#  issuerSP: "urn:gov:gsa:SAML:2.0.profiles:sp:sso:NOAA:authentication_localhost"
#  issuerIDP: "https://idp.int.identitysandbox.gov/api/saml"
#  authnContextRefs:
#    - "http://idmanagement.gov/ns/assurance/loa/1"
#    - "http://idmanagement.gov/ns/requested_attributes?ReqAttr=email"
#  authnContextComparisonType: "minimum"
#  assertionConsumerServiceURL: "https://localhost:8098/onestop/api/loginConsume"
#  assertionConsumerServiceLogoutURL: "https://localhost:8098/onestop/api/logoutConsume"
#  nameIDPolicyFormat: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
#  forceAuthn: false
#  isPassive: true
#  signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
#  signatureCanonicalizationAlgorithm: "http://www.w3.org/2001/10/xml-exc-c14n#"
#  digestAlgorithm: "http://www.w3.org/2001/04/xmlenc#sha256"
#  emailAssertionName: "email"
#  emailAssertionNameFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
#  uuidAssertionName: "uuid"
#  uuidAssertionNameFormat: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
# -----------------------------------------------------------------



spring:
  application:
    name: onestop-metadata-api
  servlet:
    multipart:
      max-file-size: 500Mb
      max-request-size: 500Mb
  h2.console.enabled: true
  h2.console.path: /h2-console
  datasource:
    # url: jdbc:h2:mem:testdb;TRACE_LEVEL_FILE=4;DB_CLOSE_ON_EXIT=FALSE # pipes logging output for h2 to console
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa # default username
    password:
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      show_sql: true
      format_sql: true
  liquibase:
    enabled: true # set to false if we don't want to run and check migrations on startup
    default-schema: PUBLIC # default schema for H2, here for documentation

management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true

logging:
  level:
    org.cedar.onestop.api.search: INFO
    org.gradle: WARN
    org.apache.http: WARN
    org.apache.http.wire: WARN
    org.apache.http.headers: WARN
    groovyx.net.http: WARN
    groovyx.net.http.HttpURLClient: WARN
    org.springframework: INFO
    org.springframework.amqp: WARN
    org.hibernate: WARN

elasticsearch:
  version: ${esVersion}
  host: localhost
  port: 9200
  max-tasks: 10
  index:
    universal-type: doc
    search:
      collection:
        name: search_collection
        pipeline-name: collection_pipeline
      granule:
        name: search_granule
        pipeline-name: granule_pipeline
      flattened-granule:
        name: search_flattened_granule
    staging:
      collection:
        name: staging_collection
      granule:
        name: staging_granule

info.version: ${version}
