server:
  port: 8098
  servlet:
    context-path: /onestop/api

spring:
  application:
    name: onestop-metadata-api
  servlet:
    multipart:
      max-file-size: 500Mb
      max-request-size: 500Mb

management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true

features.secure.upload: true

logging:
  level:
      org.cedar.onestop.api.search: INFO
      org.gradle: WARN
      org.apache.http: WARN
      org.apache.http.wire: WARN
      org.apache.http.headers: WARN
      groovyx.net.http: WARN
      groovyx.net.http.HttpURLClient: WARN
      org.springframework: INFO
      org.springframework.amqp: WARN
      org.hibernate: WARN

elasticsearch:
  version: ${esVersion}
  host: localhost
  port: 9200
  max-tasks: 10
  index:
    universal-type: doc
    search:
      collection:
        name: search_collection
        pipeline-name: collection_pipeline
      granule:
        name: search_granule
        pipeline-name: granule_pipeline
      flattened-granule:
        name: search_flattened_granule
    staging:
      collection:
        name: staging_collection
      granule:
        name: staging_granule

info.version: ${version}
