---
dependencies:
- name: cp-helm-charts
  version: ~0.1.0
  repository: https://confluentinc.github.io/cp-helm-charts/
- name: prometheus
  version: ~8.7.0
  repository: "@stable"
- name: grafana
  version: ~1.26.1
  repository: "@stable"
- name: nginx-ingress
  version: ~1.1.4
  repository: "@stable"
