# values used within cp-helm-charts
cp-helm-charts:
  cp-kafka:
    brokers: 1
    imageTag: 5.1.0
    configurationOverrides:
      offsets.topic.replication.factor: 1
    jmx:
      port: 5555
    prometheus:
      jmx:
        enabled: true
  cp-kafka-connect:
    imageTag: 5.1.0
    jmx:
      port: 5555
    prometheus:
      jmx:
        enabled: true
  cp-kafka-rest:
    imageTag: 5.1.0
    jmx:
      port: 5555
    prometheus:
      jmx:
        enabled: true
    external:
      enabled: true
      type: ClusterIP
      externalTrafficPolicy:
  cp-ksql-server:
    jmx:
      port: 5555
    prometheus:
      jmx:
        enabled: true
  cp-schema-registry:
    imageTag: 5.1.0
    configurationOverrides:
      kafkastore.topic.replication.factor: 1
    jmx:
      port: 5555
    prometheus:
      jmx:
        enabled: true
  cp-zookeeper:
    servers: 1
    imageTag: 5.1.0
    jmx:
      port: 5555
    prometheus:
      jmx:
        enabled: true

# enable/disable dependencies on cp subcharts
cp-kafka:
  enabled: true
cp-kafka-connect:
  enabled: false
cp-kafka-rest:
  enabled: false
cp-ksql-server:
  enabled: false
cp-schema-registry:
  enabled: true
cp-zookeeper:
  enabled: true

kafka-rest: {}
zookeeper: {}

prometheus:
  alertmanager:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    ingress:
      enabled: false

grafana:
  ingress:
    enabled: true
    path: /grafana
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
    - "localhost"
  "grafana.ini":
    server:
      domain: "localhost"
      root_url: "http://localhost/grafana"
  adminUser: admin
  adminPassword: admin
