---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  serviceName: registry
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: registry
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - registry
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: registry
          image: cedardevs/psi-registry
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: STATE_DIR
              value: "/var/lib/registry/data"
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
