---
apiVersion: v1
kind: ConfigMap
metadata:
  name: splitter-config
  labels:
    app: splitter
    devmode: "true"
data:
  splitter.yml: |-
    kafka:
      application:
        id: splitter
      bootstrap:
        servers: kafka:9092

    stream:
      input:
        topic: metadata-aggregator-raw-granules-changelog
      split:
        - datastreamOne:
            key: dataStream
            value: dscovr
            output:
              topic: raw-dscovr-granules
        - datastreamTwo:
            key: dataStream
            value: oer
            output:
              topic: raw-iso-granules

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitter
  labels:
    app: splitter
spec:
  selector:
    matchLabels:
      app: splitter
  template:
    metadata:
      labels:
        app: splitter
    spec:
      containers:
        - name: splitter
          image: cedardevs/psi-splitter
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: splitter-config-volume
              mountPath: /etc/splitter/config
          env:
            - name: PSI_CONFIG_LOCATION
              value: "/etc/splitter/config/splitter.yml"
      volumes:
        - name: splitter-config-volume
          configMap:
            name: splitter-config
