---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stream-manager-config
  labels:
    app: stream-manager
    devmode: "true"
data:
  splitter.yml: |-
    kafka:
      application:
        id: stream-manager
      bootstrap-servers: kafka:9092

    stream:
      split-field: dataStream
      split-values: dscovr
      topics:
        raw-granules: raw-granule
        unparsed-granules: unparsed-granule
        parsed-granules: parsed-granule
        sme-granules: sme-granule
        error-granules: error-granule

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-manager
  labels:
    app: stream-manager
spec:
  selector:
    matchLabels:
      app: stream-manager
  template:
    metadata:
      labels:
        app: stream-manager
    spec:
      containers:
        - name: stream-manager
          image: cedardevs/psi-stream-manager
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: stream-manager-config-volume
              mountPath: /etc/stream-manager/config
          env:
            - name: PSI_CONFIG_LOCATION
              value: "/etc/stream-manager/config/stream-manager.yml"
      volumes:
        - name: stream-manager-config-volume
          configMap:
            name: stream-manager-config
