---
apiVersion: v1
kind: Service
metadata:
  name: onestop-api-search
  labels:
    environment: dev
    tier: "backend"
    devmode: "true"
spec:
  selector:
    app: onestop-api-search
  ports:
  - name: http
    port: 8097
    nodePort: 30097
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onestop-api-search
  labels:
    tier: "backend"
    devmode: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onestop-api-search
  template:
    metadata:
      labels:
        app: onestop-api-search
    spec:
      containers:
      - name: onestop-api-search
        image: cedardevs/onestop-api-search
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: LOGGING_LEVEL_ORG.CEDAR.ONESTOP.API
          value: DEBUG
        - name: SPRING.CONFIG.ADDITIONAL-LOCATION
          value: /deployments/config/application.yaml
        - name: LOGIN_GOV_CLIENT_ID
          value: "urn:gov:gsa:openidconnect.profiles:sp:sso:NOAA:onestop_api_search_localhost_30000"
        - name: LOGIN_GOV_ALLOWED_ORIGIN
          value: "http://localhost:30000"
        - name: LOGIN_GOV_LOGIN_SUCCESS_REDIRECT
          value: "http://localhost:30000/onestop/"
        - name: LOGIN_GOV_LOGIN_FAILURE_REDIRECT
          value: "http://localhost:30000/onestop/"
        - name: LOGIN_GOV_LOGOUT_SUCCESS_REDIRECT
          value: "http://localhost:30000/onestop/"
        - name: LOGIN_GOV_KEYSTORE_FILE
          value: "/etc/api-search/logingov.jks"
        - name: LOGIN_GOV_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: logingov
              key: keystore_password
        - name: LOGIN_GOV_KEYSTORE_ALIAS
          valueFrom:
            secretKeyRef:
              name: logingov
              key: keystore_alias
        - name: LOGIN_GOV_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: logingov
              key: key_password
        volumeMounts:
        - name: application-config
          mountPath: "/deployments/config"
          readOnly: true
        - name: keystore
          mountPath: "/etc/api-search/logingov.jks"
          subPath: keystore.jks
        ports:
        - containerPort: 8097
      volumes:
      - name: application-config
        configMap:
          name: onestop-search-api-config
          items:
          - key: application.yaml
            path: application.yaml
      - name: keystore
        secret:
          secretName: logingov
          items:
          - key: keystore.jks
            path: keystore.jks
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: onestop-search-api-config
  labels:
    tier: "backend"
    devmode: "true"
data:
  application.yaml: |
    spring.profiles.include:
      - feature-trending-search
    ui:
      auth:
        loginEndpoint: "http://localhost:30000/onestop/api/login"
        logoutEndpoint: "http://localhost:30000/onestop/api/logout"
        userProfileEndpoint: "http://localhost:30000/onestop/api/login_profile"
      # googleAnalytics:
       # profiles:
        #  - trackingId: 'UA-127993388-1'
         #   gaOptions:
          #    userId: 127993388
       # reactGaOptions:
        #  debug: true
         # alwaysSendToDefaultTracker: false
      banner:
        message: DEMO - This site is not running on NCEI hardware, does not contain NCEI's full data holdings, and contains a limited set of its intended functionality.
      # enabledFeatureToggles:
       # - featureName: cart
      featured:
          - title: GOES Data
            searchTerm: '"Gridded Satellite GOES"'
            imageUrl: "https://www.ncdc.noaa.gov/gridsat/images/sample.png"
          - title: Digital Elevation Models
            searchTerm: '"digital elevation"'
            imageUrl: "https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_global_mosaic_hillshade/ImageServer/exportImage?bbox=-170.95,-14.40,-170.45,-14.18&size=500,500&format=png32&interpolation=%20RSP_BilinearInterpolation&renderingRule=%7B%22rasterFunction%22:%22ColorHillshade%22%7D&f=image"
          - title: NWLON and PORTS
            searchTerm: +nwlon +ports
            imageUrl: "https://data.nodc.noaa.gov/cgi-bin/gfx?id=gov.noaa.nodc:NDBC-COOPS"
          - title: Climate Data Record (CDR)
            searchTerm: '"NOAA Climate Data Record"'
            imageUrl: "https://www.ncdc.noaa.gov/sites/default/files/styles/cdr-full-width/public/cdr/AVHRRSurfaceReflectance.png"
    ---
    spring:
      profiles: feature-trending-search
    trending:
      additionalBlacklistedSearchTerms:
      - +nwlon +ports
      - '"digital elevation"'
      - '"Gridded Satellite GOES"'
      - '"NOAA Climate Data Record"'
