---
apiVersion: v1
kind: Service
metadata:
  name: onestop-client
  labels:
    environment: "dev"
    tier: "frontend"
    devmode: "true"
spec:
  selector:
    app: onestop-client
  ports:
    - name: http
      port: 80
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onestop-client
  labels:
    tier: "frontend"
    devmode: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onestop-client
  template:
    metadata:
      labels:
        app: onestop-client
    spec:
      restartPolicy: Always
      containers:
      - name: onestop-client
        image: cedardevs/onestop-client
        env:
        - name: ONESTOP_ENDPOINT
          value: onestop-api-search:8097
        - name: GEOPORTAL_ENDPOINT
          value: onestop-geoportal-search:8080
        - name: ONESTOP_ADMIN_ENDPOINT
          value: onestop-api-metadata:8098
        - name: ONESTOP_GA_TRACKING_ID
          value: UA-127993388-1
        - name: ONESTOP_GA_DEBUG
          value: true
        ports:
        - containerPort: 80
          name: http
