---
apiVersion: v1
kind: Service
metadata:
  name: onestop-api-metadata
  labels:
    environment: dev
    tier: "backend"
    devmode: "true"
spec:
  selector:
    app: onestop-api-metadata
  ports:
    - name: http
      port: 8098
      nodePort: 30098
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onestop-api-metadata
  labels:
    tier: "backend"
    devmode: "true"
spec:
  selector:
    matchLabels:
      app: onestop-api-metadata
  template:
    metadata:
      labels:
        app: onestop-api-metadata
    spec:
      containers:
      - name: onestop-api-metadata
        image: cedardevs/onestop-api-metadata
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "securitydisabled"
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: LOGGING_LEVEL_ORG.CEDAR.ONESTOP.API
          value: DEBUG
        - name: ETL_SITEMAP_DELAY_INITIAL
          value: "60000"
        - name: KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keystore
              key: keystore_password
        - name: KEYSTORE_ALIAS
          valueFrom:
            secretKeyRef:
              name: keystore
              key: keystore_alias
        - name: KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keystore
              key: key_password
        ports:
        - containerPort: 8098
        volumeMounts:
          - name: keystore
            mountPath: "/etc/api-metadata/keystore.jks"
            subPath: keystore.jks
      restartPolicy: Always
      volumes:
        - name: keystore
          secret:
            secretName: keystore
            items:
              - key: keystore.jks
                path: keystore.jks
