---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filebeat.fullname" . }}-config
  labels:
    app: {{ template "filebeat.name" . }}
    chart: {{ template "filebeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        # Mounted `filebeat-inputs` configmap:
        path: ${path.config}/inputs.d/*.yml
        # Reload inputs configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    processors:
      - add_cloud_metadata:

  {{- if and .Values.elasticsearch.cloud.id .Values.elasticsearch.cloud.auth -}}
    cloud.id: {{ .Values.elasticsearch.cloud.id }}
    cloud.auth: {{ .Values.elasticsearch.cloud.auth }}
  {{- end }}

    output.elasticsearch:
      hosts: ['{{ template "elasticsearch.serviceName" . }}:{{ template "elasticsearch.servicePort" . }}']
      username: {{ .Values.elasticsearch.username }}
      password: {{ .Values.elasticsearch.password }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filebeat.fullname" . }}-inputs
  labels:
    app: {{ template "filebeat.name" . }}
    chart: {{ template "filebeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
