apiVersion: v1
kind: Service
metadata:
  name: onestop-api-search
  labels:
    environment: dev
    tier: frontend # ?
spec:
  selector:
    app: onestop-api-search
  ports:
    - name: http
      port: 8097
      targetPort: 8097
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: onestop-api-search
  spec:
    selector:
      matchLabels:
        app: onestop-api-search
    template:
      metadata:
        labels:
          app: onestop-api-search
      spec:
        containers:
        - name: onestop-api-search
          image: cedardevs/onestop-api-search:latest
          env:
          - name: ELASTICSEARCH_HOST
            value: elasticsearch
          - name: ELASTICSEARCH_PORT
            value: "9200"
          - name: LOGGING_LEVEL_ORG.CEDAR.ONESTOP.API
            value: DEBUG
          - name: SPRING.CONFIG.ADDITIONAL-LOCATION
            value: /deployments/config/application.yaml
          volumeMounts:
          - name: application-config
            mountPath: "/deployments/config"
            readOnly: true
        volumes:
        - name: application-config
          configMap:
            name: onestop-search-api-config
            items:
            - key: application.yaml
              path: application.yaml
          ports:
          - containerPort: 8097
        restartPolicy: Always
