server:
  port: 8097
  servlet:
    context-path: /onestop/api

spring:
  application:
    name: onestop-search-api
  jmx:
    default-domain: onestop-search-api
  security:
    oauth2:
      client:
        registration:
          logingov:
            client-id: urn:gov:gsa:openidconnect.profiles:sp:sso:NOAA:onestop_user_api_localhost
            #client-secret: logingovsecret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: openid, email
        provider:
          logingov:
            authorization-uri: https://idp.int.identitysandbox.gov/openid_connect/authorize
            token-uri: https://idp.int.identitysandbox.gov/api/openid_connect/token
            user-info-uri: https://idp.int.identitysandbox.gov/api/openid_connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://idp.int.identitysandbox.gov/api/openid_connect/certs

logingov:
  allowed-origin: ${allowedOrigin}
  login-success-redirect: ${loginSuccessRedirect}
  logout-success-redirect: ${logoutSuccessRedirect}
  keystore:
    alias: ${keystoreAlias}
    file: ${keystorePath}/${keystoreFile}
    password: ${keystorePassword}
    #keyPassword: \${keyPassword}
    type: JKS

management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true

features.sitemap: false

logging:
  level:
      org.cedar.onestop.api.search: INFO
      org.gradle: WARN
      org.apache.http: WARN
      org.apache.http.wire: WARN
      org.apache.http.headers: WARN
      groovyx.net.http: WARN
      groovyx.net.http.HttpURLClient: WARN
      org.springframework: INFO
      org.springframework.amqp: WARN
      org.hibernate: WARN

elasticsearch:
  version: ${esVersion}
  host: localhost
  port: 9200
  index:
    universal-type: doc
    sitemap:
      name: sitemap
    search:
      collection:
        name: search_collection
      granule:
        name: search_granule
      flattened-granule:
        name: search_flattened_granule

search:
  minimumShouldMatch: 75%
  tieBreaker: 0
  phraseSlop: 0
  fields:
    title: 4
    description: 2
    keywords: 3
    fileIdentifier: 1
    parentIdentifier: 1
    doi: 1
    beginDate: 1
    endDate: 1
    spatialBounding: 1
    dsmmAverage: 1

info.version: ${version}
info.buildDate: ${buildDate}

ui:
  auth:
    loginEndpoint: "http://localhost:8080/onestop/api/login"
    logoutEndpoint: "http://localhost:8080/onestop/api/logout"
    userProfileEndpoint: "http://localhost:8080/onestop/api/login_profile"