server:
  port: 8097
  context-path: /onestop/api

spring:
  application:
    name: onestop-search-api

logging:
  level:
      org.cedar.onestop.api.search: INFO
      org.gradle: WARN
      org.apache.http: WARN
      org.apache.http.wire: WARN
      org.apache.http.headers: WARN
      groovyx.net.http: WARN
      groovyx.net.http.HttpURLClient: WARN
      org.springframework: INFO
      org.springframework.amqp: WARN
      org.hibernate: WARN

elasticsearch:
  version: ${esVersion}
  host: localhost
  port: 9200
  index:
    universal-type: doc
    search:
      collection:
        name: search_collection
      granule:
        name: search_granule
      flattenedGranule:
        name: search_flattened_granule

search:
  minimumShouldMatch: 75%
  tieBreaker: 0
  phraseSlop: 0
  fields:
    title: 4
    alternateTitle: 4
    description: 1
    keywords: 2
    gcmdScience: 2
    gcmdLocations: 2
    gcmdInstruments: 2
    gcmdPlatforms: 2
    gcmdProjects: 2
    gcmdDataCenters: 2
    gcmdDataResolution: 2
    topicCategories: 1 # different than keywords?
    fileIdentifier: 1
    internalParentIdentifier: 1
    temporalBounding:
      beginDate: 1
      endDate: 1
      instant: 1
    spatialBounding: 1
    dataFormats:
      analyzed: 1
#      NESTED (cannot be individually boosted):
#    acquisitionInstruments:
#      instrumentIdentifier: 1
#      instrumentType: 1  # not analyzed... should we search it?
#      instrumentDescription: 1
#    acquisitionOperations:
#      operationDescription: 1
#      operationIdentifier: 1
#      operationType: 1
#    acquisitionPlatforms:
#      platformIdentifier: 1
#      platformDescription: 1
#      platformSponsor: 1
#    contacts:
#      organizationName: 1
#      individualName: 1
    modifiedDate: 1  # why?
    creationDate: 1  # why?
    revisionDate: 1  # why?
    publicationDate: 1  # why?
    dsmmAverage: 1
    _all: 1

info.version: ${version}
info.buildDate: ${buildDate}
