---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onestop-registry.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "onestop-registry.name" . }}
    helm.sh/chart: {{ include "onestop-registry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
  - port: 9090
    targetPort: db
    name: db
  selector:
    app: {{ include "onestop-registry.name" . }}
    release: {{ .Release.Name }}
