kafka:
  application:
    id: stream-manager
  bootstrap-servers: kafka:9092

stream:
  split-field: dataStream
  split-values: dscovr
  topics:
    raw-granules: raw-granule
    unparsed-granules: unparsed-granule
    parsed-granules: parsed-granule
    sme-granules: sme-granule
    error-granules: error-granule