openapi: 3.0.0
info:
  title: Granule API
  version: 2.0.0
paths:
  /granule:
    head:
      tags:
        - granule
      summary: Get Granule Info
      responses:
        '200':
          description: Successful operation
    get:
      tags:
        - granule
      summary: Get Granule Info
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: 'schema/response.json#/infoResponse'
  '/granule/{id}':
    head:
      tags:
        - granule
      summary: Granule by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the granule
      responses:
        '200':
          description: Successful operation
        '404':
          description: Request Parsing Error
    get:
      tags:
        - granule
      summary: Granule by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the granule
      responses:
        '200':
          description: Successful operation
        '404':
          description: Request Parsing Error
  /search/granule:
    post:
      tags:
        - granule
      summary: Retrieve granule metadata
      description: 'Retrieve granule metadata records matching the text query string, spatial, and/or temporal filter.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'file:src/main/resources/schema/request.json'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: 'schema/response.json#/searchResponse'
        '400':
          description: Bad Request
