kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume
  labels:
    environment: dev
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
