# Tasks to install and start the onestop api application
---

- name: Ensure the latest java is installed
  become: true
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: latest

- name: Create a onestop group
  become: true
  group:
    name: onestop
    state: present

- name: Create a onestop user
  become: true
  user:
    name: onestop
    group: onestop
    state: present

- name: Download latest api snapshot
  become: true
  maven_artifact:
    repository_url: https://oss.jfrog.org/oss-snapshot-local
    group_id: cires.ncei.onestop
    artifact_id: onestop-api
    version: latest
    dest: /usr/local/bin/onestop-api.jar
    state: present
  register: download

- name: Stop the api service if the jar changed
  become: true
  service:
    name: onestop-api
    state: stopped
  when: download.changed

- name: Link the api app into system services
  become: true
  file:
    path: /etc/init.d/onestop-api
    state: link
    src: "{{ download.dest }}"

- name: Start the api as a system service
  become: true
  service:
    name: onestop-api
    state: started
    enabled: true