# Tasks to install and start the onestop api application
---

- name: Ensure the latest java is installed
  become: true
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: latest

- name: Create a onestop group
  become: true
  group:
    name: onestop
    state: present

- name: Create a onestop user
  become: true
  user:
    name: onestop
    group: onestop
    state: present

- name: Download latest api snapshot
  become: true
  maven_artifact:
    repository_url: https://oss.jfrog.org/oss-snapshot-local
    group_id: cires.ncei.onestop
    artifact_id: onestop-api
    version: latest
    extension: war
    dest: /usr/local/bin/onestop-api.war
    state: present
  register: download

- name: Set the permissions on the api app
  become: true
  file:
    path: "{{ download.dest }}"
    owner: onestop
    group: onestop
    mode: 440

- name: Install the api conf file
  become: true
  template:
    src: templates/onestop-api.conf
    dest: /usr/local/bin/onestop-api.conf
    owner: onestop
    group: onestop
    mode: 440
  register: conf

#   CAN'T USE UNTIL ANSIBLE V2.2
#- name: Stop the api service if something changed
#  become: true
#  systemd:
#    name: onestop-api
#    state: stopped
#  when: download.changed or conf.changed

- name: Stop the api service if something changed
  become: true
  service:
    name: onestop-api
    state: stopped
  when: download.changed or conf.changed

- name: Install the api as a systemd service
  become: true
  template:
    src: templates/onestop-api.service
    dest: /etc/systemd/system/onestop-api.service
    owner: root
    group: root
    mode: 664

#   CAN'T USE UNTIL ANSIBLE V2.2
#- name: Start the api as a system service
#  become: true
#  systemd:
#    name: onestop-api
#    daemon_reload: yes
#    state: "{{ 'restarted' if download.changed or conf.changed else 'started'}}"
#    enabled: true

- name: Start the api as a system service
  become: true
  service:
    name: onestop-api
    state: "{{ 'restarted' if download.changed or conf.changed else 'started'}}"
    enabled: true
