# Tasks to install and start the onestop api application
---

- name: Ensure the latest java is installed
  become: true
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: latest

- name: Create a onestop group
  become: true
  group:
    name: onestop
    state: present

- name: Create a onestop user
  become: true
  user:
    name: onestop
    group: onestop
    state: present

- name: Get stats on the currently deployed jar
  stat:
    path: /usr/local/bin/onestop-api.jar
  register: currentjar

- name: Get stats on the jar being deployed
  connection: local
  stat:
    path: "{{ apiJar }}"
  register: newjar

- name: Stop the api service if we need to update it
  service:
    name: onestop-api
    state: stopped
  when: currentjar.stat.exists and currentjar.stat.checksum != newjar.stat.checksum

- name: Install the api app
  become: true
  copy:
    src: "{{ apiJar }}"
    dest: /usr/local/bin/onestop-api.jar
    owner: onestop
    group: onestop
    mode: u=rx,g=,o=
  register: deployedjar

- name: Link the api app into system services
  become: true
  file:
    path: /etc/init.d/onestop-api
    state: link
    src: "{{ deployedjar.dest }}"

- name: Start the api as a system service
  become: true
  service:
    name: onestop-api
    state: started
    enabled: true