apiVersion: v1
entries:
  onestop:
  - apiVersion: v1
    appVersion: 2.4.0
    created: "2019-10-18T13:37:20.462208-06:00"
    description: A Helm chart for the OneStop system
    digest: 309d3cc84b3acbdd2cca7d68fd16fe4acbb70106b9289de449e6b4b798eb0c37
    name: onestop
    urls:
    - onestop-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2019-10-18T13:37:20.45746-06:00"
    description: A Helm chart for the OneStop system
    digest: a38e89b18d2fdb850b206cceb3525fb36a0ed6ef78a10765eda3b0b2cc3f7895
    name: onestop
    urls:
    - onestop-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2019-10-18T13:37:20.45535-06:00"
    description: A Helm chart for the OneStop system
    digest: 965fd23b5088778b98daec5564c03db77261bf8b1f7077bef8b53ddd0bbb76b8
    name: onestop
    urls:
    - onestop-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2019-10-18T13:37:20.453814-06:00"
    description: A Helm chart for the OneStop system
    digest: 0b792e2abf7c8c66bbf4f663cbda50d85b6fa23ca8bd2acdfa34d87f3a61317f
    name: onestop
    urls:
    - onestop-0.1.0.tgz
    version: 0.1.0
generated: "2019-10-18T13:37:20.451265-06:00"
