apiVersion: v1
entries:
  onestop:
  - apiVersion: v1
    appVersion: 2.1.0
    created: 2019-03-29T12:39:20.974753-06:00
    description: A Helm chart for the OneStop system
    digest: 52f4b4ae8a68d3130384560faedbccfed22e2e6c0cd78a5d34c0eb07b3ddcf35
    name: onestop
    urls:
    - onestop/onestop-0.1.0.tgz
    version: 0.1.0
generated: 2019-03-29T12:39:20.972937-06:00
