apiVersion: v1
entries:
  psi:
  - apiVersion: v1
    appVersion: 1.1.2-SNAPSHOT
    created: "2019-09-16T14:41:23.307076-06:00"
    description: A Helm chart for the Persistent Streaming Inventory system
    digest: 106352660fe7706a59ad81e1bab3bfd1ff3b224db71e6ce3ce9eefc57aa0df08
    name: psi
    urls:
    - psi-0.2.0.tgz
    version: 0.2.0
generated: "2019-09-16T14:41:23.303194-06:00"
