apiVersion: v1
entries:
  onestop:
  - apiVersion: v1
    appVersion: 2.2.0
    created: 2019-06-21T16:39:47.992339-06:00
    description: A Helm chart for the OneStop system
    digest: b46830ee57297f9ca820d87e425d1ea44a7cfff4c94d000576af2dda4979f1fc
    name: onestop
    urls:
    - onestop-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 2.1.0
    created: 2019-06-21T16:39:47.991328-06:00
    description: A Helm chart for the OneStop system
    digest: 0b792e2abf7c8c66bbf4f663cbda50d85b6fa23ca8bd2acdfa34d87f3a61317f
    name: onestop
    urls:
    - onestop-0.1.0.tgz
    version: 0.1.0
generated: 2019-06-21T16:39:47.989447-06:00
