server:
  port: 3000

kafka:
  bootstrap:
    servers: localhost:9092
  granule:
    topic: dscovr-topic

spring.kafka.consumer.group-id: dscovr-group

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.concretepage: DEBUG